### ISSUE TITLE
provide CodeLab for Location

### ISSUE THREAD

**Issue by RoyMontoya** [Nearsoft/android-school#25]
Create code lab for android school class 4.

- create markdown with step by step process to add location service to TODOapp

**Comment by jmsalcido** [comment]
change name: https://github.com/Nearsoft/androidschool/tree/master/2017/feb_event/todoapp/codelab/25mar2017 we dont have event this day.

**Comment by jmsalcido** [comment]
btw try to follow this convention:
https://github.com/Nearsoft/androidschool/tree/master/2017/feb_event/todoapp/codelab/25Feb2017
