### ISSUE TITLE
Issue4-create UI - Main Activity

### ISSUE THREAD

**Issue by CarlosMiguelCuevas** [Nearsoft/android-school#4]
the main activity UI:
- a recycler view (will show all the 'TODO Items')
- a FAB to add new 'TODO items' 

the `TODO item` UI (a card view with):
- the name on the `TODO task`
- a checkbox to mark as completed
- the expiration date
- any other field that you think is needed

**Comment by CarlosMiguelCuevas** [comment]
I'll take this, Ivan already work a little bit with this, but I'll add fake data to show and I'll add some missing fields

**Comment by ivan** [comment]
Please don't type @ivan into github it sends me an email

**Comment by CarlosMiguelCuevas** [comment]
jajjajaja Sorry I'll change that

**Comment by CarlosMiguelCuevas** [comment]
PR: https://github.com/Nearsoft/androidschool/pull/10

**Comment by jmsalcido** [comment]
@ivanebernal fyi -> Carlos already finished this and I fixed some stuff over: https://github.com/Nearsoft/androidschool/commit/67475cd730e752245b9e4cd817d0f42ecd84f892

it is on branch `patch-for-ivan` in case that you would like to see and merge it, just let me know.
