### ISSUE TITLE
Create UI - Add new 'TODO Item'

### ISSUE THREAD

**Issue by CarlosMiguelCuevas** [Nearsoft/android-school#5]
A new activity to create new item/task.
Fields:
 - task name
 - date / time
 - place
 -  extra infromation - renamed to notes

FAB to save.

**Comment by CarlosMiguelCuevas** [comment]
there is already an activity for view the detail of a current task, but there are some missing fields.

**Comment by jmsalcido** [comment]
@RoyMontoya please take this one

**Comment by jmsalcido** [comment]
is this done? @RoyMontoya

**Comment by RoyMontoya** [comment]
@jmsalcido this issue has been solved and merged with PR "Issue5 - UI and some logic #16" . Closing issue
