### ISSUE TITLE
Create Binding between activities and adding functionality 

### ISSUE THREAD

**Issue by CarlosMiguelCuevas** [Nearsoft/android-school#6]
Actions:
- when open the main activity we should see the list of items
- when clicking the FAB in the main activity we should open up the add activity 
- when clicking the FAB in the add activity we should see the main activity with the new item in the list 
-when the checkbox in the card view is tap we should mark the task as done (maybe delete it from the list)
-delete the item (a contextual menu or swapping the item)

**Comment by jmsalcido** [comment]
is this done? @RoyMontoya

**Comment by RoyMontoya** [comment]
@jmsalcido this issue was also solved and merged with PR "Issue5 - UI and some logic #16" . Closing issue
